### ISSUE TITLE
New Release with updates?

### ISSUE THREAD

**Issue by rlam3** [dhamaniasad/Flask-WhooshAlchemy#8]
New Release with updates?

**Comment by dhamaniasad** [comment]
If there are no more fixes, I will have a `0.7.1` release out by the end of the month.

**Comment by rlam3** [comment]
Thank you!

**Comment by rlam3** [comment]
quick question.... if i use redux. does that mean i don't need the unsupported version of flask-whooshalchemy that was forked ? or is this just adding extra functionality/extension?

in addition, where should you put whoosh base folder? within the app itself? or should it be outside for instance... /var/www/whoosh_base ? I'm currently trying to use this with flask and ajax... but it seems really slow on a live server ... and i'm not sure if it has anything to do with where the folder is placed or permissions?

**Comment by dhamaniasad** [comment]
@rlam3 You want to use either Redux or the original. If you add both you might get conflicts. Redux is only incorporating the open pull requests(for fixes), since the original has been abandoned. 

Personally, I put my whoosh folder some place like `~/whoosh_index`. Where you put the folder should not matter in terms of speed. If you have used Solr or the like in the past, Whoosh will be noticeably slower in comparison. 

If you have hundreds of thousands of rows indexed, searching might take a few seconds. Is it much slower than that?

**Comment by rlam3** [comment]
@dhamaniasad

~/whoosh_index would be in the root folder? 

It feels kinda laggish. It does return within a few seconsd but I'm trying to do a search as you type kind of ajax call. Do you have an example of ajax with flask-whooshalchemy? sometimes when I type a bit faster my searchfield, it seems that the request is sent through fast enough but retrieving and Model.query.pure_whoosh('xyz') and then serializing the object with marshmallow takes longer than expected in production. I'm not having as much issue with local development.

**Comment by dhamaniasad** [comment]
@rlam3 No, that would be the home folder of whatever user is running your Flask app. 

Whoosh wouldn't really excel at search-as-you-type. Your interface will feel pretty laggy if you do that. Maybe your production environment has a bigger database than your development environment?

**Comment by rlam3** [comment]
@dhamaniasad  my development env currently has the exact same amount of records as my production database. it is more like staging but i already notice the difference in speed between development being faster than prod/staging. what do you recommend the better way to implement search as you type ?

**Comment by dhamaniasad** [comment]
@rlam3 I have released `0.7.1` on PyPI. 

Perhaps the difference in speed is coming from network overhead? Whoosh is pretty slow compared to something like ElasticSearch, so that might be a better choice for search-as-you-type. 

I have never implemented a search-as-you-type system in Flask-WhooshAlchemy, so without looking at some code, I cannot really give any suggestions for speed improvements. 

Also, apologies for the delay.
